// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package store

import (
	"context"
	"database/sql"
)

const listCourses = `-- name: ListCourses :many
SELECT id, name, street, city, state, zip_code, phone, cost
FROM courses
ORDER BY id
`

type ListCoursesRow struct {
	ID      int64
	Name    sql.NullString
	Street  sql.NullString
	City    sql.NullString
	State   sql.NullString
	ZipCode sql.NullString
	Phone   sql.NullString
	Cost    sql.NullString
}

func (q *Queries) ListCourses(ctx context.Context) ([]ListCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesRow
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Street,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Phone,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
