// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (course_id, date, tee_time, open_spots, number_of_holes, private, host_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, course_id, date, tee_time, open_spots, number_of_holes, private, host_id
`

type CreateEventParams struct {
	CourseID      sql.NullInt32
	Date          sql.NullString
	TeeTime       sql.NullString
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        sql.NullInt32
}

type CreateEventRow struct {
	ID            int64
	CourseID      sql.NullInt32
	Date          sql.NullString
	TeeTime       sql.NullString
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        sql.NullInt32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.CourseID,
		arg.Date,
		arg.TeeTime,
		arg.OpenSpots,
		arg.NumberOfHoles,
		arg.Private,
		arg.HostID,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.TeeTime,
		&i.OpenSpots,
		&i.NumberOfHoles,
		&i.Private,
		&i.HostID,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT e.id, e.course_id, e.date, e.tee_time, e.open_spots, e.number_of_holes,
       e.private, e.host_id, c.name AS course_name, p.name AS host_name
FROM events e
JOIN courses c ON c.id = e.course_id
JOIN players p ON p.id = e.host_id
WHERE e.id = $1
`

type GetEventByIDRow struct {
	ID            int64
	CourseID      sql.NullInt32
	Date          sql.NullString
	TeeTime       sql.NullString
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        sql.NullInt32
	CourseName    sql.NullString
	HostName      sql.NullString
}

func (q *Queries) GetEventByID(ctx context.Context, id int64) (GetEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.TeeTime,
		&i.OpenSpots,
		&i.NumberOfHoles,
		&i.Private,
		&i.HostID,
		&i.CourseName,
		&i.HostName,
	)
	return i, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT e.id, e.course_id, e.date, e.tee_time, e.open_spots, e.number_of_holes,
       e.private, e.host_id, c.name AS course_name, p.name AS host_name
FROM events e
JOIN courses c ON c.id = e.course_id
JOIN players p ON p.id = e.host_id
ORDER BY e.id
`

type ListAllEventsRow struct {
	ID            int64
	CourseID      sql.NullInt32
	Date          sql.NullString
	TeeTime       sql.NullString
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        sql.NullInt32
	CourseName    sql.NullString
	HostName      sql.NullString
}

func (q *Queries) ListAllEvents(ctx context.Context) ([]ListAllEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEventsRow
	for rows.Next() {
		var i ListAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Date,
			&i.TeeTime,
			&i.OpenSpots,
			&i.NumberOfHoles,
			&i.Private,
			&i.HostID,
			&i.CourseName,
			&i.HostName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByPlayerID = `-- name: ListEventsByPlayerID :many
SELECT e.id, e.course_id, e.date, e.tee_time, e.open_spots, e.number_of_holes,
       e.private, e.host_id, c.name AS course_name, p.name AS host_name
FROM events e
JOIN courses c ON c.id = e.course_id
JOIN players p ON p.id = e.host_id
JOIN player_events pe ON pe.event_id = e.id
WHERE pe.player_id = $1
ORDER BY e.id
`

type ListEventsByPlayerIDRow struct {
	ID            int64
	CourseID      sql.NullInt32
	Date          sql.NullString
	TeeTime       sql.NullString
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        sql.NullInt32
	CourseName    sql.NullString
	HostName      sql.NullString
}

func (q *Queries) ListEventsByPlayerID(ctx context.Context, playerID sql.NullInt64) ([]ListEventsByPlayerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByPlayerIDRow
	for rows.Next() {
		var i ListEventsByPlayerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Date,
			&i.TeeTime,
			&i.OpenSpots,
			&i.NumberOfHoles,
			&i.Private,
			&i.HostID,
			&i.CourseName,
			&i.HostName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEvents = `-- name: ListPublicEvents :many
SELECT e.id, e.course_id, e.date, e.tee_time, e.open_spots, e.number_of_holes,
       e.private, e.host_id, c.name AS course_name, p.name AS host_name
FROM events e
JOIN courses c ON c.id = e.course_id
JOIN players p ON p.id = e.host_id
WHERE e.private = false
ORDER BY e.id
`

type ListPublicEventsRow struct {
	ID            int64
	CourseID      sql.NullInt32
	Date          sql.NullString
	TeeTime       sql.NullString
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        sql.NullInt32
	CourseName    sql.NullString
	HostName      sql.NullString
}

func (q *Queries) ListPublicEvents(ctx context.Context) ([]ListPublicEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicEventsRow
	for rows.Next() {
		var i ListPublicEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Date,
			&i.TeeTime,
			&i.OpenSpots,
			&i.NumberOfHoles,
			&i.Private,
			&i.HostID,
			&i.CourseName,
			&i.HostName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
