// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package store

import (
	"context"
	"database/sql"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (follower_id, followee_id, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, follower_id, followee_id
`

type CreateFriendshipParams struct {
	FollowerID sql.NullInt32
	FolloweeID sql.NullInt32
}

type CreateFriendshipRow struct {
	ID         int64
	FollowerID sql.NullInt32
	FolloweeID sql.NullInt32
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (CreateFriendshipRow, error) {
	row := q.db.QueryRowContext(ctx, createFriendship, arg.FollowerID, arg.FolloweeID)
	var i CreateFriendshipRow
	err := row.Scan(&i.ID, &i.FollowerID, &i.FolloweeID)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE follower_id = $1 AND followee_id = $2
`

type DeleteFriendshipParams struct {
	FollowerID sql.NullInt32
	FolloweeID sql.NullInt32
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.FollowerID, arg.FolloweeID)
	return err
}

const findFriendship = `-- name: FindFriendship :one
SELECT id, follower_id, followee_id
FROM friendships
WHERE follower_id = $1 AND followee_id = $2
`

type FindFriendshipParams struct {
	FollowerID sql.NullInt32
	FolloweeID sql.NullInt32
}

type FindFriendshipRow struct {
	ID         int64
	FollowerID sql.NullInt32
	FolloweeID sql.NullInt32
}

func (q *Queries) FindFriendship(ctx context.Context, arg FindFriendshipParams) (FindFriendshipRow, error) {
	row := q.db.QueryRowContext(ctx, findFriendship, arg.FollowerID, arg.FolloweeID)
	var i FindFriendshipRow
	err := row.Scan(&i.ID, &i.FollowerID, &i.FolloweeID)
	return i, err
}

const listFolloweeIDsByFollowerID = `-- name: ListFolloweeIDsByFollowerID :many
SELECT followee_id
FROM friendships
WHERE follower_id = $1
`

func (q *Queries) ListFolloweeIDsByFollowerID(ctx context.Context, followerID sql.NullInt32) ([]sql.NullInt32, error) {
	rows, err := q.db.QueryContext(ctx, listFolloweeIDsByFollowerID, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt32
	for rows.Next() {
		var followee_id sql.NullInt32
		if err := rows.Scan(&followee_id); err != nil {
			return nil, err
		}
		items = append(items, followee_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
