// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_events.sql

package store

import (
	"context"
	"database/sql"
)

const closePendingForEvent = `-- name: ClosePendingForEvent :exec
UPDATE player_events
SET invite_status = 3, updated_at = NOW()
WHERE event_id = $1 AND invite_status = 0
`

func (q *Queries) ClosePendingForEvent(ctx context.Context, eventID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, closePendingForEvent, eventID)
	return err
}

const countAcceptedForEvent = `-- name: CountAcceptedForEvent :one
SELECT COUNT(*) FROM player_events
WHERE event_id = $1 AND invite_status = 1
`

func (q *Queries) CountAcceptedForEvent(ctx context.Context, eventID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAcceptedForEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayerEvent = `-- name: CreatePlayerEvent :one
INSERT INTO player_events (player_id, event_id, invite_status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, player_id, event_id, invite_status
`

type CreatePlayerEventParams struct {
	PlayerID     sql.NullInt64
	EventID      sql.NullInt64
	InviteStatus sql.NullInt32
}

type CreatePlayerEventRow struct {
	ID           int64
	PlayerID     sql.NullInt64
	EventID      sql.NullInt64
	InviteStatus sql.NullInt32
}

func (q *Queries) CreatePlayerEvent(ctx context.Context, arg CreatePlayerEventParams) (CreatePlayerEventRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayerEvent, arg.PlayerID, arg.EventID, arg.InviteStatus)
	var i CreatePlayerEventRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.EventID,
		&i.InviteStatus,
	)
	return i, err
}

const getPlayerEvent = `-- name: GetPlayerEvent :one
SELECT id, player_id, event_id, invite_status
FROM player_events
WHERE player_id = $1 AND event_id = $2
`

type GetPlayerEventParams struct {
	PlayerID sql.NullInt64
	EventID  sql.NullInt64
}

type GetPlayerEventRow struct {
	ID           int64
	PlayerID     sql.NullInt64
	EventID      sql.NullInt64
	InviteStatus sql.NullInt32
}

func (q *Queries) GetPlayerEvent(ctx context.Context, arg GetPlayerEventParams) (GetPlayerEventRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerEvent, arg.PlayerID, arg.EventID)
	var i GetPlayerEventRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.EventID,
		&i.InviteStatus,
	)
	return i, err
}

const listAcceptedEventIDsByPlayerID = `-- name: ListAcceptedEventIDsByPlayerID :many
SELECT event_id
FROM player_events
WHERE player_id = $1 AND invite_status = 1
`

func (q *Queries) ListAcceptedEventIDsByPlayerID(ctx context.Context, playerID sql.NullInt64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptedEventIDsByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt64
	for rows.Next() {
		var event_id sql.NullInt64
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerIDsByEventAndStatus = `-- name: ListPlayerIDsByEventAndStatus :many
SELECT player_id
FROM player_events
WHERE event_id = $1 AND invite_status = $2
`

type ListPlayerIDsByEventAndStatusParams struct {
	EventID      sql.NullInt64
	InviteStatus sql.NullInt32
}

func (q *Queries) ListPlayerIDsByEventAndStatus(ctx context.Context, arg ListPlayerIDsByEventAndStatusParams) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerIDsByEventAndStatus, arg.EventID, arg.InviteStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt64
	for rows.Next() {
		var player_id sql.NullInt64
		if err := rows.Scan(&player_id); err != nil {
			return nil, err
		}
		items = append(items, player_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersExceptHost = `-- name: ListPlayersExceptHost :many
SELECT id FROM players WHERE id != $1
`

func (q *Queries) ListPlayersExceptHost(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPlayersExceptHost, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenClosedForEvent = `-- name: ReopenClosedForEvent :exec
UPDATE player_events
SET invite_status = 0, updated_at = NOW()
WHERE event_id = $1 AND invite_status = 3
`

func (q *Queries) ReopenClosedForEvent(ctx context.Context, eventID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, reopenClosedForEvent, eventID)
	return err
}

const updatePlayerEventStatus = `-- name: UpdatePlayerEventStatus :one
UPDATE player_events
SET invite_status = $3, updated_at = NOW()
WHERE player_id = $1 AND event_id = $2
RETURNING id, player_id, event_id, invite_status
`

type UpdatePlayerEventStatusParams struct {
	PlayerID     sql.NullInt64
	EventID      sql.NullInt64
	InviteStatus sql.NullInt32
}

type UpdatePlayerEventStatusRow struct {
	ID           int64
	PlayerID     sql.NullInt64
	EventID      sql.NullInt64
	InviteStatus sql.NullInt32
}

func (q *Queries) UpdatePlayerEventStatus(ctx context.Context, arg UpdatePlayerEventStatusParams) (UpdatePlayerEventStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerEventStatus, arg.PlayerID, arg.EventID, arg.InviteStatus)
	var i UpdatePlayerEventStatusRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.EventID,
		&i.InviteStatus,
	)
	return i, err
}
