// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package store

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name, phone, email, username, password_digest, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, name, phone, email, username
`

type CreatePlayerParams struct {
	Name           sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Username       sql.NullString
	PasswordDigest sql.NullString
}

type CreatePlayerRow struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.PasswordDigest,
	)
	var i CreatePlayerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, name, phone, email, username, password_digest
FROM players
WHERE email = $1
`

type GetPlayerByEmailRow struct {
	ID             int64
	Name           sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Username       sql.NullString
	PasswordDigest sql.NullString
}

func (q *Queries) GetPlayerByEmail(ctx context.Context, email sql.NullString) (GetPlayerByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByEmail, email)
	var i GetPlayerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
		&i.PasswordDigest,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, name, phone, email, username
FROM players
WHERE id = $1
`

type GetPlayerByIDRow struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

func (q *Queries) GetPlayerByID(ctx context.Context, id int64) (GetPlayerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, id)
	var i GetPlayerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, phone, email, username
FROM players
ORDER BY id
`

type ListPlayersRow struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

func (q *Queries) ListPlayers(ctx context.Context) ([]ListPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
