// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (player_id, body, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, player_id, body, created_at
`

type CreatePostParams struct {
	PlayerID int64
	Body     string
}

type CreatePostRow struct {
	ID        int64
	PlayerID  int64
	Body      string
	CreatedAt time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.PlayerID, arg.Body)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND player_id = $2
`

type DeletePostParams struct {
	ID       int64
	PlayerID int64
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.PlayerID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT p.id, p.player_id, p.body, p.created_at, pl.name AS player_name
FROM posts p
JOIN players pl ON pl.id = p.player_id
WHERE p.id = $1
`

type GetPostByIDRow struct {
	ID         int64
	PlayerID   int64
	Body       string
	CreatedAt  time.Time
	PlayerName sql.NullString
}

func (q *Queries) GetPostByID(ctx context.Context, id int64) (GetPostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Body,
		&i.CreatedAt,
		&i.PlayerName,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.player_id, p.body, p.created_at, pl.name AS player_name
FROM posts p
JOIN players pl ON pl.id = p.player_id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32
	Offset int32
}

type ListPostsRow struct {
	ID         int64
	PlayerID   int64
	Body       string
	CreatedAt  time.Time
	PlayerName sql.NullString
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Body,
			&i.CreatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
