// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package store

import (
	"context"
	"database/sql"
)

const createReaction = `-- name: CreateReaction :one
INSERT INTO reactions (post_id, player_id, emoji, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, post_id, player_id, emoji
`

type CreateReactionParams struct {
	PostID   int64
	PlayerID int64
	Emoji    string
}

type CreateReactionRow struct {
	ID       int64
	PostID   int64
	PlayerID int64
	Emoji    string
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (CreateReactionRow, error) {
	row := q.db.QueryRowContext(ctx, createReaction, arg.PostID, arg.PlayerID, arg.Emoji)
	var i CreateReactionRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.PlayerID,
		&i.Emoji,
	)
	return i, err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions
WHERE post_id = $1 AND player_id = $2 AND emoji = $3
`

type DeleteReactionParams struct {
	PostID   int64
	PlayerID int64
	Emoji    string
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteReaction, arg.PostID, arg.PlayerID, arg.Emoji)
	return err
}

const findReaction = `-- name: FindReaction :one
SELECT id, post_id, player_id, emoji
FROM reactions
WHERE post_id = $1 AND player_id = $2 AND emoji = $3
`

type FindReactionParams struct {
	PostID   int64
	PlayerID int64
	Emoji    string
}

type FindReactionRow struct {
	ID       int64
	PostID   int64
	PlayerID int64
	Emoji    string
}

func (q *Queries) FindReaction(ctx context.Context, arg FindReactionParams) (FindReactionRow, error) {
	row := q.db.QueryRowContext(ctx, findReaction, arg.PostID, arg.PlayerID, arg.Emoji)
	var i FindReactionRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.PlayerID,
		&i.Emoji,
	)
	return i, err
}

const listReactionsByPostID = `-- name: ListReactionsByPostID :many
SELECT r.id, r.post_id, r.player_id, r.emoji, pl.name AS player_name
FROM reactions r
JOIN players pl ON pl.id = r.player_id
WHERE r.post_id = $1
ORDER BY r.id
`

type ListReactionsByPostIDRow struct {
	ID         int64
	PostID     int64
	PlayerID   int64
	Emoji      string
	PlayerName sql.NullString
}

func (q *Queries) ListReactionsByPostID(ctx context.Context, postID int64) ([]ListReactionsByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionsByPostIDRow
	for rows.Next() {
		var i ListReactionsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PlayerID,
			&i.Emoji,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
