// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replies.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createReply = `-- name: CreateReply :one
INSERT INTO replies (post_id, player_id, body, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, post_id, player_id, body, created_at
`

type CreateReplyParams struct {
	PostID   int64
	PlayerID int64
	Body     string
}

type CreateReplyRow struct {
	ID        int64
	PostID    int64
	PlayerID  int64
	Body      string
	CreatedAt time.Time
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) (CreateReplyRow, error) {
	row := q.db.QueryRowContext(ctx, createReply, arg.PostID, arg.PlayerID, arg.Body)
	var i CreateReplyRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.PlayerID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReply = `-- name: DeleteReply :exec
DELETE FROM replies WHERE id = $1 AND player_id = $2
`

type DeleteReplyParams struct {
	ID       int64
	PlayerID int64
}

func (q *Queries) DeleteReply(ctx context.Context, arg DeleteReplyParams) error {
	_, err := q.db.ExecContext(ctx, deleteReply, arg.ID, arg.PlayerID)
	return err
}

const getReplyByID = `-- name: GetReplyByID :one
SELECT r.id, r.post_id, r.player_id, r.body, r.created_at, pl.name AS player_name
FROM replies r
JOIN players pl ON pl.id = r.player_id
WHERE r.id = $1
`

type GetReplyByIDRow struct {
	ID         int64
	PostID     int64
	PlayerID   int64
	Body       string
	CreatedAt  time.Time
	PlayerName sql.NullString
}

func (q *Queries) GetReplyByID(ctx context.Context, id int64) (GetReplyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReplyByID, id)
	var i GetReplyByIDRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.PlayerID,
		&i.Body,
		&i.CreatedAt,
		&i.PlayerName,
	)
	return i, err
}

const listRepliesByPostID = `-- name: ListRepliesByPostID :many
SELECT r.id, r.post_id, r.player_id, r.body, r.created_at, pl.name AS player_name
FROM replies r
JOIN players pl ON pl.id = r.player_id
WHERE r.post_id = $1
ORDER BY r.created_at ASC
`

type ListRepliesByPostIDRow struct {
	ID         int64
	PostID     int64
	PlayerID   int64
	Body       string
	CreatedAt  time.Time
	PlayerName sql.NullString
}

func (q *Queries) ListRepliesByPostID(ctx context.Context, postID int64) ([]ListRepliesByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepliesByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesByPostIDRow
	for rows.Next() {
		var i ListRepliesByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PlayerID,
			&i.Body,
			&i.CreatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
